version: "3.8"
services:
  balda:
    image: ghcr.io/henerator/balda-front/balda-front:latest
    container_name: balda-front
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/roman-balda.ru:/etc/ssl-sertificates:ro
      - /etc/letsencrypt/archive:/archive
